// ── ch3_load/data.js ──
const CODE_BOOT = [
  "pub fn rust_main() -> ! {",
  "    clear_bss();",
  "    logging::init();",
  "    mm::init();",
  "    trap::init();",
  "    task::add_initproc();",
  "    task::run_first_task();",
  "}"
];
const CODE_LOADER = [
  "pub fn load_apps() {",
  "    let num = get_num_app();",
  "    for i in 0..num {",
  "        let base = APP_BASE + i * APP_SIZE_LIMIT;",
  "        copy_app_data_to(base);",
  "        init_app_cx(i, base);",
  "    }",
  "}"
];
const CODE_TASK = [
  "impl TaskControlBlock {",
  "    pub fn new(i: usize) -> Self {",
  "        let (ustack, trap_cx, entry) = build_user_space(i);",
  "        let kstack_top = KStack::new(i).get_top();",
  "        *trap_cx = TrapContext::app_init_context(entry, ustack, KERNEL_TOKEN, kstack_top, trap_handler as usize);",
  "        let task_cx = TaskContext::goto_restore(kstack_top - core::mem::size_of::<TrapContext>());",
  "        Self { status: Ready, task_cx, kstack_top }",
  "    }",
  "}"
];

const REGIONS = [
  {id:"app1", cls:"r-app1", name:"App1 Slot", top:"0x80420000", low:"0x80400000", reason:"APP_BASE + 1*APP_SIZE_LIMIT"},
  {id:"app0", cls:"r-app0", name:"App0 Slot", top:"0x80400000", low:"0x803e0000", reason:"APP_BASE + 0*APP_SIZE_LIMIT"},
  {id:"kernel", cls:"r-kernel", name:"Kernel", top:"0x80280000", low:"0x80200000", reason:"tutorial linker layout"}
];

const STEPS = [
  {
    title:"Enter rust_main",
    file:"os/src/main.rs",
    code:CODE_BOOT, line:0,
    desc:"Kernel entry. No task loaded yet.",
    regs:{mode:"S", stvec:"-", current:"-", num_app:0},
    active:["kernel"],
    tasks:[
      {id:0,status:"Init",base:"-",kstack:"-"},
      {id:1,status:"Init",base:"-",kstack:"-"}
    ]
  },
  {
    title:"trap::init sets stvec",
    file:"os/src/trap/mod.rs",
    code:CODE_BOOT, line:4,
    desc:"Trap vector points to __alltraps in Direct mode.",
    regs:{mode:"S", stvec:"__alltraps", current:"-", num_app:0},
    active:["kernel"],
    tasks:[
      {id:0,status:"Init",base:"-",kstack:"-"},
      {id:1,status:"Init",base:"-",kstack:"-"}
    ]
  },
  {
    title:"loader gets app count",
    file:"os/src/loader.rs",
    code:CODE_LOADER, line:1,
    desc:"Read app metadata table generated by build script.",
    regs:{mode:"S", stvec:"__alltraps", current:"-", num_app:2},
    active:["kernel"],
    tasks:[
      {id:0,status:"Init",base:"-",kstack:"-"},
      {id:1,status:"Init",base:"-",kstack:"-"}
    ]
  },
  {
    title:"Load app0 to slot0",
    file:"os/src/loader.rs",
    code:CODE_LOADER, line:4,
    desc:"Copy app0 image to APP_BASE + 0 * APP_SIZE_LIMIT.",
    regs:{mode:"S", stvec:"__alltraps", current:"-", num_app:2},
    active:["kernel","app0"],
    tasks:[
      {id:0,status:"Init",base:"0x80400000",kstack:"-"},
      {id:1,status:"Init",base:"-",kstack:"-"}
    ]
  },
  {
    title:"Build TCB for task0",
    file:"os/src/task/task.rs",
    code:CODE_TASK, line:5,
    desc:"Create trap context on kstack0 and task context (ra=__restore).",
    regs:{mode:"S", stvec:"__alltraps", current:"-", num_app:2},
    active:["kernel","app0"],
    tasks:[
      {id:0,status:"Ready",base:"0x80400000",kstack:"0x80282000"},
      {id:1,status:"Init",base:"-",kstack:"-"}
    ]
  },
  {
    title:"Load app1 to slot1",
    file:"os/src/loader.rs",
    code:CODE_LOADER, line:4,
    desc:"Copy app1 image to APP_BASE + 1 * APP_SIZE_LIMIT.",
    regs:{mode:"S", stvec:"__alltraps", current:"-", num_app:2},
    active:["kernel","app1"],
    tasks:[
      {id:0,status:"Ready",base:"0x80400000",kstack:"0x80282000"},
      {id:1,status:"Init",base:"0x80420000",kstack:"-"}
    ]
  },
  {
    title:"Build TCB for task1",
    file:"os/src/task/task.rs",
    code:CODE_TASK, line:5,
    desc:"Create trap context on kstack1 and task context for first restore.",
    regs:{mode:"S", stvec:"__alltraps", current:"-", num_app:2},
    active:["kernel","app1"],
    tasks:[
      {id:0,status:"Ready",base:"0x80400000",kstack:"0x80282000"},
      {id:1,status:"Ready",base:"0x80420000",kstack:"0x80285000"}
    ]
  },
  {
    title:"TaskManager initialized",
    file:"os/src/task/manager.rs",
    code:["TASK_MANAGER = [task0, task1];","current_task = 0;"], line:1,
    desc:"Scheduler metadata is ready. No user code executed yet.",
    regs:{mode:"S", stvec:"__alltraps", current:"0", num_app:2},
    active:["kernel"],
    tasks:[
      {id:0,status:"Ready",base:"0x80400000",kstack:"0x80282000"},
      {id:1,status:"Ready",base:"0x80420000",kstack:"0x80285000"}
    ]
  },
  {
    title:"run_first_task -> Task0 Running",
    file:"os/src/task/mod.rs",
    code:["pub fn run_first_task() {","    tasks[0].status = Running;","    __switch(...);","}"], line:2,
    desc:"Switch from boot context to task0 context. Next visible flow enters __restore.",
    regs:{mode:"S", stvec:"__alltraps", current:"0", num_app:2},
    active:["kernel","app0"],
    tasks:[
      {id:0,status:"Running",base:"0x80400000",kstack:"0x80282000"},
      {id:1,status:"Ready",base:"0x80420000",kstack:"0x80285000"}
    ]
  }
];
