// ── ch2/trap/data.js ──
// Trap 처리 전 과정: run_next_app → __restore → User → ecall → __alltraps → trap_handler → __restore

// ── 코드 스니펫 ──
const CODE_RUN_NEXT_APP = [
  '// os/src/batch.rs',
  'pub fn run_next_app() -> ! {',
  '    let mut app_manager = APP_MANAGER.exclusive_access();',
  '    let current_app = app_manager.get_current_app();',
  '    app_manager.load_app(current_app);  // → 0x80400000',
  '    app_manager.move_to_next_app();',
  '    drop(app_manager);',
  '    unsafe {',
  '        __restore(KERNEL_STACK.push_context(',
  '            TrapContext::app_init_context(',
  '                APP_BASE_ADDRESS,     // 0x80400000',
  '                USER_STACK.get_sp(), // user_stack_top',
  '            )',
  '        ) as *const _ as usize);',
  '    }',
  '    panic!("Unreachable!");',
  '}',
];

const CODE_APP_INIT_CONTEXT = [
  '// os/src/trap/context.rs',
  'pub fn app_init_context(entry: usize, sp: usize) -> Self {',
  '    let mut sstatus = sstatus::read();',
  '    sstatus.set_spp(SPP::User);  // → sret 후 U-mode',
  '    let mut cx = Self {',
  '        x: [0; 32],',
  '        sstatus,',
  '        sepc: entry,          // 0x80400000',
  '    };',
  '    cx.set_sp(sp);            // x[2] = user_stack_top',
  '    cx',
  '}',
];

const CODE_PUSH_CONTEXT = [
  '// os/src/batch.rs',
  'pub fn push_context(&self, cx: TrapContext)',
  '        -> &\'static mut TrapContext {',
  '    // cx_ptr = kernel_stack_top - size_of::<TrapContext>()',
  '    //        = kernel_stack_top - 272',
  '    let cx_ptr = (self.get_sp()',
  '        - core::mem::size_of::<TrapContext>())',
  '        as *mut TrapContext;',
  '    unsafe { *cx_ptr = cx; }  // kernel stack에 복사',
  '    unsafe { cx_ptr.as_mut().unwrap() } // 주소 반환',
  '}',
  '// → __restore(cx_ptr as usize)',
];

const CODE_RESTORE = [
  '# os/src/trap/trap.S',
  '__restore:',
  '    mv sp, a0              # sp = TrapContext 주소',
  '    ld t0, 32*8(sp)        # t0 = sstatus',
  '    ld t1, 33*8(sp)        # t1 = sepc',
  '    ld t2, 2*8(sp)         # t2 = user sp',
  '    csrw sstatus, t0',
  '    csrw sepc,    t1',
  '    csrw sscratch, t2      # sscratch ← user_sp',
  '    ld x1, 1*8(sp)         # ra',
  '    ld x3, 3*8(sp)         # gp',
  '    # ... ld x5~x31 ...',
  '    addi sp, sp, 34*8      # sp ← kernel_stack_top',
  '    csrrw sp, sscratch, sp # sp ↔ sscratch 교환',
  '    sret                   # PC←sepc, mode←SPP',
];

const CODE_USER_ECALL = [
  '# user/src/syscall.rs',
  'fn syscall(id: usize, args: [usize; 3]) -> isize {',
  '    let ret: isize;',
  '    unsafe {',
  '        asm!("ecall",',
  '            inlateout("a0") args[0] => ret,',
  '            in("a1") args[1],',
  '            in("a2") args[2],',
  '            in("a7") id,',
  '        );',
  '    }',
  '    ret',
  '}',
  '// ecall 실행 → hardware trap 발생!',
];

const CODE_ALLTRAPS = [
  '# os/src/trap/trap.S',
  '__alltraps:',
  '    csrrw sp, sscratch, sp # sp ↔ sscratch',
  '    # sp=kernel_top, sscratch=user_sp',
  '    addi sp, sp, -34*8     # TrapContext 공간 확보',
  '    sd x1, 1*8(sp)         # ra',
  '    sd x3, 3*8(sp)         # gp',
  '    # ... sd x5~x31 ...',
  '    csrr t0, sstatus',
  '    csrr t1, sepc',
  '    sd t0, 32*8(sp)        # TrapContext.sstatus',
  '    sd t1, 33*8(sp)        # TrapContext.sepc',
  '    csrr t2, sscratch      # t2 = user_sp',
  '    sd t2, 2*8(sp)         # TrapContext.x[2]',
  '    mv a0, sp',
  '    call trap_handler',
];

const CODE_TRAP_HANDLER = [
  '// os/src/trap/mod.rs',
  'pub fn trap_handler(cx: &mut TrapContext)',
  '        -> &mut TrapContext {',
  '    let scause = scause::read();',
  '    match scause.cause() {',
  '        Trap::Exception(Exception::UserEnvCall) => {',
  '            cx.sepc += 4;          // ecall 다음으로',
  '            cx.x[10] = syscall(    // a0 = 반환값',
  '                cx.x[17],          // a7 = syscall ID',
  '                [cx.x[10], cx.x[11], cx.x[12]]',
  '            ) as usize;',
  '        }',
  '        Trap::Exception(Exception::StoreFault) |',
  '        Trap::Exception(Exception::IllegalInstruction) => {',
  '            run_next_app();',
  '        }',
  '        _ => { panic!("Unsupported trap"); }',
  '    }',
  '    cx',
  '}',
];

// ── SVG 상태 정의 ──
// sp: 'ks_top' | 'tcx_bot' | 'us_top' | 'user_run'
// sscratch: 'us_top' | 'ks_top' | 'unknown'
// tcx: bool (TrapContext visible on kernel stack)
// tcxHL: highlighted fields []
// tcxVals: field values object
// mode: 'S' | 'U' | 'trap'
// phase: 'init'|'restore'|'user'|'alltraps'|'handler'

const STEPS = [
  // ── Phase 0: 첫 앱 실행 준비 ──
  {
    title: 'run_next_app() — app_0 적재 (0x80400000)',
    file: 'os/src/batch.rs',
    code: CODE_RUN_NEXT_APP, line: 4,
    svg: { tcx: false, sp:'ks_top', ss:'unknown', mode:'S', phase:'init' },
    regs: { sp:'kernel_top', ss:'─', sepc:'─', scause:'─', mode:'S-mode' },
    desc: '커널이 app_0을 0x80400000에 복사합니다.\n\n• load_app(0): APP_BASE_ADDRESS에 memcpy\n• fence.i: 명령 캐시 플러시\n• move_to_next_app(): current_app += 1\n\n이후 push_context() + __restore()로\n첫 앱을 실행합니다.',
    detail: 'APP_BASE_ADDRESS = 0x80400000. 모든 앱이 이 고정 주소에 순서대로 로드됩니다. 단순 batch 방식 — 동시 실행 없음.',
  },
  {
    title: 'app_init_context() — 초기 TrapContext 구성',
    file: 'os/src/trap/context.rs',
    code: CODE_APP_INIT_CONTEXT, line: 3,
    svg: { tcx: false, sp:'ks_top', ss:'unknown', mode:'S', phase:'init',
           pending: { sepc:'0x80400000', x2:'0x80412000', sstatus:'SPP=U', x10:'0', x17:'0' } },
    regs: { sp:'kernel_top', ss:'─', sepc:'─', scause:'─', mode:'S-mode' },
    desc: 'TrapContext 구조체를 초기화합니다.\n\n핵심 필드:\n• sepc  = 0x80400000  → sret 후 PC\n• sstatus.SPP = User  → sret 후 U-mode\n• x[2] = user_stack_top → 유저 sp\n\n아직 커널 스택에 배치되기 전입니다.',
    detail: 'TrapContext = 34 × 8 = 272 bytes (x[0..31] + sstatus + sepc). 처음 실행이지만 "trap 복귀 프레임"과 완전히 같은 형태.',
  },
  {
    title: 'push_context() — TrapContext를 커널 스택에 배치',
    file: 'os/src/batch.rs :: push_context()',
    code: CODE_PUSH_CONTEXT, line: 8,
    svg: { tcx: true, sp:'tcx_bot', ss:'unknown', mode:'S', phase:'init',
           tcxVals:{ sepc:'0x80400000', x2:'0x80412000', sstatus:'SPP=U', x10:'0x0', x17:'0x0' },
           tcxHL:[] },
    regs: { sp:'ks_top - 272', ss:'─', sepc:'─', scause:'─', mode:'S-mode' },
    desc: 'TrapContext를 커널 스택 최상단에 배치합니다.\n\n  kernel_stack_top    (0x80282000)\n  ─── 272 bytes ───\n  TrapContext start   (0x80281EF0) ← sp\n\npush_context()는 TrapContext 시작 주소를 반환합니다.\n이 주소가 __restore의 a0 인자로 전달됩니다.',
    detail: 'KERNEL_STACK_SIZE = 4096 * 2 = 8192 bytes. TrapContext는 top 바로 아래에 위치합니다.',
  },
  // ── Phase 1: __restore → U-mode ──
  {
    title: '__restore: mv sp, a0 — sp = TrapContext 주소',
    file: 'os/src/trap/trap.S :: __restore',
    code: CODE_RESTORE, line: 2,
    svg: { tcx: true, sp:'tcx_bot', ss:'unknown', mode:'S', phase:'restore',
           tcxVals:{ sepc:'0x80400000', x2:'0x80412000', sstatus:'SPP=U', x10:'0x0', x17:'0x0' },
           tcxHL:[] },
    regs: { sp:'tcx_start (= a0)', ss:'─', sepc:'─', scause:'─', mode:'S-mode' },
    desc: '`mv sp, a0`로 sp를 TrapContext 시작 주소로 설정합니다.\n\n이후 모든 ld는 이 sp 기준 오프셋으로 필드를 읽습니다:\n  sp+0*8  = x[0]      sp+2*8  = x[2](user sp)\n  sp+17*8 = x[17]     sp+32*8 = sstatus\n  sp+33*8 = sepc',
    detail: '__restore는 두 가지 경로로 진입: ① 최초 앱 실행 (지금) ② trap 처리 후 복귀. 두 경우 모두 동일한 코드.',
  },
  {
    title: '__restore: CSR 복원 — sscratch ← user_sp',
    file: 'os/src/trap/trap.S :: __restore',
    code: CODE_RESTORE, line: 3,
    svg: { tcx: true, sp:'tcx_bot', ss:'us_top', mode:'S', phase:'restore',
           tcxVals:{ sepc:'0x80400000', x2:'0x80412000', sstatus:'SPP=U', x10:'0x0', x17:'0x0' },
           tcxHL:['sstatus','sepc','x2'] },
    regs: { sp:'tcx_start', ss:'0x80412000', sepc:'0x80400000', scause:'─', mode:'S-mode' },
    desc: 'ld t0=sstatus, t1=sepc, t2=x[2]=user_sp\n\ncsrw sstatus, t0  → CPU sstatus = SPP=User\ncsrw sepc,    t1  → CPU sepc = 0x80400000\ncsrw sscratch, t2 → sscratch = user_stack_top\n\nsscratch에 user_sp를 보관하는 이유:\n  아직 sp는 TrapContext를 가리키므로,\n  user_sp를 지금 sp에 넣을 수 없기 때문입니다.',
    detail: 'sscratch는 이후 csrrw로 sp와 교환됩니다. trap이 오면 다시 한 번 교환되어 kernel_top이 복구됩니다.',
  },
  {
    title: '__restore: x1~x31 복원',
    file: 'os/src/trap/trap.S :: __restore',
    code: CODE_RESTORE, line: 9,
    svg: { tcx: true, sp:'tcx_bot', ss:'us_top', mode:'S', phase:'restore',
           tcxVals:{ sepc:'0x80400000', x2:'0x80412000', sstatus:'SPP=U', x10:'0x0', x17:'0x0' },
           tcxHL:['x1','x3-x31'] },
    regs: { sp:'tcx_start', ss:'0x80412000', sepc:'0x80400000', scause:'─', mode:'S-mode' },
    desc: '일반 레지스터를 TrapContext에서 복원합니다.\n\n  ld x1(ra), ld x3(gp)\n  ld x5~x31 (t0-t6, a0-a7, s0-s11)\n\n첫 실행이라 대부분 0입니다.\n\nx2(sp)는 지금 복원하지 않습니다 —\n  sp가 바뀌면 TrapContext를 더 이상 읽을 수 없으므로\n  마지막 csrrw에서 처리합니다.',
    detail: 'x4(tp)는 건너뜁니다 — rCore 앱이 thread pointer를 사용하지 않기 때문.',
  },
  {
    title: '__restore: addi sp, sp, 34*8 → sp = kernel_stack_top',
    file: 'os/src/trap/trap.S :: __restore',
    code: CODE_RESTORE, line: 12,
    svg: { tcx: true, sp:'ks_top', ss:'us_top', mode:'S', phase:'restore',
           tcxVals:{ sepc:'0x80400000', x2:'0x80412000', sstatus:'SPP=U', x10:'0x0', x17:'0x0' },
           tcxHL:[] },
    regs: { sp:'ks_top (0x80282000)', ss:'0x80412000', sepc:'0x80400000', scause:'─', mode:'S-mode' },
    desc: '`addi sp, sp, 34*8`으로 TrapContext(272 bytes)를 해제합니다.\n\n  sp: tcx_start → kernel_stack_top\n  (= 0x80281EF0 + 272 = 0x80282000)\n\nTrapContext는 더 이상 활성 프레임이 아닙니다.\nsscratch는 여전히 user_stack_top을 가리킵니다.',
    detail: '"해제"는 sp 증가만으로 이루어집니다. 데이터는 메모리에 남지만 더 이상 사용하지 않습니다.',
  },
  {
    title: '__restore: csrrw + sret → U-mode 진입!',
    file: 'os/src/trap/trap.S :: __restore',
    code: CODE_RESTORE, line: 13,
    svg: { tcx: false, sp:'us_top', ss:'ks_top', mode:'U', phase:'restore',
           tcxVals:{}, tcxHL:[] },
    regs: { sp:'us_top (0x80412000)', ss:'ks_top (0x80282000)', sepc:'0x80400000', scause:'─', mode:'U-mode' },
    desc: '`csrrw sp, sscratch, sp` 교환:\n  전: sp=kernel_top,  sscratch=user_sp\n  후: sp=user_sp,     sscratch=kernel_top\n\n`sret`:\n  ① PC ← sepc = 0x80400000\n  ② mode ← sstatus.SPP = U-mode\n\n앱이 유저 모드에서 실행됩니다!',
    detail: 'sscratch = kernel_stack_top. 다음 trap 때 csrrw로 다시 교환하여 커널 스택을 복구합니다.',
  },
  // ── Phase 2: 유저 실행 + ecall ──
  {
    title: '유저 앱 실행 중 (U-mode @ 0x80400000)',
    file: 'user/src/main.rs (U-mode)',
    code: CODE_USER_ECALL, line: 0,
    svg: { tcx: false, sp:'us_top', ss:'ks_top', mode:'U', phase:'user',
           tcxVals:{}, tcxHL:[] },
    regs: { sp:'user_sp', ss:'ks_top', sepc:'─', scause:'─', mode:'U-mode' },
    desc: '유저 앱이 U-mode에서 실행 중입니다.\n\n• sp = 유저 스택 (자라는 중)\n• sscratch = kernel_stack_top (trap용 보관)\n\nsyscall 호출 시 ecall 사용:\n  a7 = syscall ID (예: 64 = sys_write)\n  a0~a2 = 인자\n  a0 = 반환값 (ecall 후)',
    detail: 'U-mode에서는 CSR 직접 접근 불가. S-mode 리소스 접근은 반드시 ecall을 통해야 합니다.',
  },
  {
    title: 'ecall 실행 → 하드웨어 trap 발생',
    file: 'user/src/syscall.rs (U-mode)',
    code: CODE_USER_ECALL, line: 13,
    svg: { tcx: false, sp:'us_top', ss:'ks_top', mode:'trap', phase:'user',
           tcxVals:{}, tcxHL:[] },
    regs: { sp:'user_sp', ss:'ks_top', sepc:'ecall_pc', scause:'0x8 (UserEnvCall)', mode:'S-mode ←!' },
    desc: '`ecall` 명령 실행 → 하드웨어가 즉시 처리:\n\n① sepc ← PC (ecall 명령 주소)\n② scause ← 8 (UserEnvCall)\n③ mode ← S-mode\n④ PC ← stvec = __alltraps 주소\n\n일반 레지스터는 하드웨어가 저장하지 않습니다!\n→ __alltraps가 소프트웨어로 커널 스택에 저장해야 합니다.',
    detail: 'stvec는 커널 init()에서 __alltraps 주소로 설정됩니다. Direct 모드 — 모든 trap이 동일 진입점으로.',
  },
  // ── Phase 3: __alltraps ──
  {
    title: '__alltraps: csrrw sp, sscratch, sp',
    file: 'os/src/trap/trap.S :: __alltraps',
    code: CODE_ALLTRAPS, line: 2,
    svg: { tcx: false, sp:'ks_top', ss:'us_top', mode:'S', phase:'alltraps',
           tcxVals:{}, tcxHL:[] },
    regs: { sp:'ks_top (0x80282000)', ss:'user_sp', sepc:'ecall_pc', scause:'0x8', mode:'S-mode' },
    desc: '`csrrw sp, sscratch, sp` 교환:\n  전: sp=user_sp,     sscratch=kernel_top\n  후: sp=kernel_top,  sscratch=user_sp\n\n커널 스택이 확보되었습니다.\nsscratch에 user_sp가 보관됩니다 (나중에 TrapContext.x[2]에 저장).',
    detail: 'trap 진입 시 첫 명령이 이 csrrw. RISC-V의 한 명령으로 스택 전환 — x86보다 훨씬 깔끔합니다.',
  },
  {
    title: '__alltraps: addi sp, sp, -34*8 → TrapContext 공간 확보',
    file: 'os/src/trap/trap.S :: __alltraps',
    code: CODE_ALLTRAPS, line: 4,
    svg: { tcx: true, sp:'tcx_bot', ss:'us_top', mode:'S', phase:'alltraps',
           tcxVals:{ sepc:'?', x2:'?', sstatus:'?', x10:'?', x17:'?' },
           tcxHL:[] },
    regs: { sp:'tcx_start (= ks_top-272)', ss:'user_sp', sepc:'ecall_pc', scause:'0x8', mode:'S-mode' },
    desc: '`addi sp, sp, -34*8`으로 TrapContext 272 bytes 공간 확보:\n\n  sp: kernel_stack_top → kernel_stack_top - 272\n\n이 공간에 trap 이전 CPU 상태를 저장할 것입니다.\n아직 내용은 채워지지 않았습니다 (?).',
    detail: 'TrapContext = x[0..31](256B) + sstatus(8B) + sepc(8B) = 272 bytes.',
  },
  {
    title: '__alltraps: sd x1~x31 → TrapContext 저장',
    file: 'os/src/trap/trap.S :: __alltraps',
    code: CODE_ALLTRAPS, line: 5,
    svg: { tcx: true, sp:'tcx_bot', ss:'us_top', mode:'S', phase:'alltraps',
           tcxVals:{ sepc:'?', x2:'?', sstatus:'?', x10:'a0(fd)', x17:'64(write)' },
           tcxHL:['x1','x3-x31'] },
    regs: { sp:'tcx_start', ss:'user_sp', sepc:'ecall_pc', scause:'0x8', mode:'S-mode' },
    desc: '일반 레지스터를 TrapContext에 저장합니다.\n\n  sd x1(ra), sd x3(gp)\n  sd x5~x31 ...\n\n저장된 syscall 인자:\n  TrapContext.x[17] = a7 = 64 (sys_write)\n  TrapContext.x[10] = a0 = fd\n\nx2(sp)는 지금 저장 안 합니다 — sscratch에 있는 user_sp를 나중에 씁니다.',
    detail: 't0/t1/t2는 이미 커널 스택에 저장되었으므로, CSR 읽기에 자유롭게 사용할 수 있습니다.',
  },
  {
    title: '__alltraps: sstatus/sepc/user_sp 저장 → call trap_handler',
    file: 'os/src/trap/trap.S :: __alltraps',
    code: CODE_ALLTRAPS, line: 9,
    svg: { tcx: true, sp:'tcx_bot', ss:'us_top', mode:'S', phase:'alltraps',
           tcxVals:{ sepc:'ecall_pc', x2:'user_sp', sstatus:'SPP=U', x10:'fd', x17:'64' },
           tcxHL:['sstatus','sepc','x2'] },
    regs: { sp:'tcx_start (=a0)', ss:'user_sp', sepc:'ecall_pc', scause:'0x8', mode:'S-mode' },
    desc: 'CSR과 user_sp를 TrapContext에 저장합니다.\n\n  csrr t0, sstatus  → sd t0, 32*8(sp)\n  csrr t1, sepc     → sd t1, 33*8(sp)\n  csrr t2, sscratch → sd t2, 2*8(sp) (user_sp)\n\nTrapContext 완성! mv a0, sp → call trap_handler\n\nRust 함수에 TrapContext 주소 전달.',
    detail: 'sscratch에서 user_sp를 꺼내어 TrapContext.x[2]에 저장. TrapContext는 이제 trap 이전 CPU 상태의 완전한 스냅샷.',
  },
  // ── Phase 4: trap_handler ──
  {
    title: 'trap_handler: scause 확인 → syscall 처리',
    file: 'os/src/trap/mod.rs :: trap_handler()',
    code: CODE_TRAP_HANDLER, line: 4,
    svg: { tcx: true, sp:'tcx_bot', ss:'us_top', mode:'S', phase:'handler',
           tcxVals:{ sepc:'ecall_pc', x2:'user_sp', sstatus:'SPP=U', x10:'fd', x17:'64' },
           tcxHL:['x17'] },
    regs: { sp:'tcx_start', ss:'user_sp', sepc:'ecall_pc', scause:'0x8 (UserEnvCall)', mode:'S-mode' },
    desc: 'trap_handler가 scause를 읽어 분기합니다.\n\n  scause = 0x8 → UserEnvCall\n\n처리:\n  cx.sepc += 4       ← ecall 다음 명령으로 복귀\n  cx.x[10] = syscall(cx.x[17], ...)\n             ↑ a7=64: sys_write 처리 후 반환값 → a0\n\ncx는 TrapContext의 직접 참조 — 메모리가 실제로 수정됩니다!',
    detail: '경로 B: StoreFault / IllegalInstruction → run_next_app() → 다음 앱 실행.',
  },
  {
    title: 'trap_handler 반환 — TrapContext 수정 완료',
    file: 'os/src/trap/mod.rs → trap.S :: __restore',
    code: CODE_TRAP_HANDLER, line: 19,
    svg: { tcx: true, sp:'tcx_bot', ss:'us_top', mode:'S', phase:'handler',
           tcxVals:{ sepc:'ecall_pc+4', x2:'user_sp', sstatus:'SPP=U', x10:'write_ret', x17:'64' },
           tcxHL:['sepc','x10'] },
    regs: { sp:'tcx_start', ss:'user_sp', sepc:'ecall_pc+4', scause:'0x8', mode:'S-mode' },
    desc: 'trap_handler가 수정된 cx를 반환합니다.\n\n변경된 필드:\n  TrapContext.sepc   = ecall_pc + 4   ← 다음 명령\n  TrapContext.x[10]  = write_result   ← syscall 반환값\n\nreturn cx → __restore가 수정된 TrapContext로 CPU 복원\n\n경로 A: 같은 앱 다음 명령으로 복귀\n경로 B: run_next_app()으로 다음 앱 시작',
    detail: '__alltraps의 "call trap_handler" 직후 __restore 코드로 계속됩니다 (trap.S에서 연속).',
  },
  {
    title: '__restore → sret → U-mode 복귀 (경로 A)',
    file: 'os/src/trap/trap.S :: __restore → sret',
    code: CODE_RESTORE, line: 13,
    svg: { tcx: false, sp:'us_top', ss:'ks_top', mode:'U', phase:'restore',
           tcxVals:{}, tcxHL:[] },
    regs: { sp:'user_sp', ss:'ks_top', sepc:'ecall_pc+4', scause:'0x8', mode:'U-mode' },
    desc: '__restore가 수정된 TrapContext로 CPU를 복원합니다.\n\n① ld sstatus/sepc/user_sp → CSR 복원\n② ld x1~x31 (x[10]=write_ret → a0에 반영)\n③ addi sp, 34*8 → sp = kernel_stack_top\n④ csrrw → sp=user_sp, sscratch=kernel_top\n⑤ sret → PC=ecall+4, mode=User\n\n유저 앱의 a0 = syscall 반환값으로 실행 재개!',
    detail: '경로 B: run_next_app() → 새 TrapContext 생성 → __restore로 다른 앱 시작. ch2는 preemption이 없으므로 타이머 인터럽트에 의한 전환은 없습니다.',
  },
];
