// ── ch2/batch/data.js ──
// trap_handler 이후 경로 분기: Path A (same app) vs Path B (next app)

const CODE_TRAP_HANDLER = [
  '// os/src/trap/mod.rs',
  'pub fn trap_handler(cx: &mut TrapContext)',
  '        -> &mut TrapContext {',
  '    let scause = scause::read();',
  '    match scause.cause() {',
  '',
  '        // ─── 경로 A: syscall ───',
  '        Trap::Exception(Exception::UserEnvCall) => {',
  '            cx.sepc += 4;',
  '            cx.x[10] = syscall(',
  '                cx.x[17], [cx.x[10], cx.x[11], cx.x[12]]',
  '            ) as usize;',
  '        }',
  '',
  '        // ─── 경로 B: 치명적 예외 ───',
  '        Trap::Exception(Exception::StoreFault)   |',
  '        Trap::Exception(Exception::StorePageFault) |',
  '        Trap::Exception(Exception::IllegalInstruction) => {',
  '            println!("[kernel] killed app");',
  '            run_next_app();  // ← 현재 앱 종료, 다음 앱 시작',
  '        }',
  '        _ => { panic!("Unsupported trap"); }',
  '    }',
  '    cx  // 경로 A: 수정된 cx 반환',
  '}',
];

const CODE_RESTORE_A = [
  '# 경로 A: __restore → 같은 앱 복귀',
  '__restore:',
  '    mv sp, a0              # sp = 수정된 TrapContext',
  '    ld t0, 32*8(sp)        # sstatus (SPP=User)',
  '    ld t1, 33*8(sp)        # sepc = ecall_pc + 4  ← 수정됨',
  '    ld t2, 2*8(sp)         # user_sp',
  '    csrw sstatus, t0',
  '    csrw sepc, t1',
  '    csrw sscratch, t2',
  '    ld x1~x31 ...          # x[10] = syscall_ret ← 수정됨',
  '    addi sp, sp, 34*8      # sp = kernel_stack_top',
  '    csrrw sp, sscratch, sp # sp = user_sp',
  '    sret  # PC = ecall+4, a0 = syscall_ret, U-mode',
];

const CODE_RUN_NEXT = [
  '// 경로 B: run_next_app() → 다음 앱 실행',
  'pub fn run_next_app() -> ! {',
  '    let mut app_manager = APP_MANAGER.exclusive_access();',
  '    let current_app = app_manager.get_current_app();',
  '    app_manager.load_app(current_app);  // 다음 앱 로드',
  '    app_manager.move_to_next_app();',
  '    drop(app_manager);',
  '    unsafe {',
  '        __restore(KERNEL_STACK.push_context(',
  '            TrapContext::app_init_context(',
  '                APP_BASE_ADDRESS,     // 0x80400000',
  '                USER_STACK.get_sp(),  // user_stack_top (초기화)',
  '            )',
  '        ) as *const _ as usize);',
  '    }',
  '    panic!("Unreachable!");',
  '}',
];

// 각 스텝의 분기 상태
// path: 'none' | 'A' | 'B'
// stage: 'handler' | 'A_restore' | 'A_user' | 'B_load' | 'B_restore' | 'B_user'
const STEPS = [
  {
    title: 'trap_handler: scause 확인',
    file: 'os/src/trap/mod.rs',
    code: CODE_TRAP_HANDLER, line: 3,
    path: 'none', stage: 'handler',
    desc: 'trap_handler가 scause를 읽어 처리 경로를 결정합니다.\n\nscause 값에 따라 두 경로로 분기합니다:\n  0x8 (UserEnvCall) → 경로 A: syscall 처리 후 같은 앱\n  StoreFault / IllegalInstruction → 경로 B: 다음 앱',
    detail: 'ch2 batch 모델: timer interrupt가 없으므로 preemptive scheduling 없음. 앱 교체는 오직 예외/종료 syscall로만.',
  },
  {
    title: '경로 A: UserEnvCall — cx.sepc += 4',
    file: 'os/src/trap/mod.rs (경로 A)',
    code: CODE_TRAP_HANDLER, line: 8,
    path: 'A', stage: 'handler',
    desc: '[경로 A] scause = 0x8 (UserEnvCall: ecall from U-mode)\n\ncx.sepc += 4\n  → ecall 명령(4 bytes)을 건너뜁니다.\n  → sret 후 ecall 다음 명령부터 재개됩니다.\n\n이 수정은 TrapContext.sepc를 직접 씁니다.\n(커널 스택 위의 메모리를 수정)',
    detail: 'sepc를 += 4하지 않으면 sret 후 다시 ecall로 돌아가 무한루프가 됩니다.',
  },
  {
    title: '경로 A: cx.x[10] = syscall 반환값',
    file: 'os/src/trap/mod.rs (경로 A)',
    code: CODE_TRAP_HANDLER, line: 9,
    path: 'A', stage: 'handler',
    desc: '[경로 A] cx.x[10] = syscall(cx.x[17], ...) as usize\n\n  cx.x[17] = a7 = syscall ID (예: 64 = sys_write)\n  cx.x[10] = a0 = 첫 번째 인자\n  cx.x[11] = a1 = 두 번째 인자\n  cx.x[12] = a2 = 세 번째 인자\n\nsyscall 처리 후 반환값을 TrapContext.x[10](=a0)에 저장합니다.\n  → sret 후 유저 코드의 a0 = 반환값',
    detail: 'RISC-V SBI/syscall 규약: a7=ID, a0~a2=인자, a0=반환값. TrapContext를 통해 레지스터를 수정하는 방식.',
  },
  {
    title: '경로 A: return cx → __restore',
    file: 'os/src/trap/mod.rs (경로 A)',
    code: CODE_TRAP_HANDLER, line: 23,
    path: 'A', stage: 'A_restore',
    desc: '[경로 A] trap_handler가 수정된 cx를 반환합니다.\n\n반환된 cx 주소 = a0 → __restore 진입\n\n수정된 필드:\n  sepc    → ecall_pc + 4  (다음 명령)\n  x[10]  → syscall 반환값 (a0)\n\n__restore가 이 TrapContext로 CPU 상태를 복원합니다.',
    detail: '__restore는 __alltraps의 "call trap_handler" 바로 다음에 위치합니다 (trap.S에서 연속).',
  },
  {
    title: '경로 A: __restore → sret → 같은 앱 복귀',
    file: 'os/src/trap/trap.S :: __restore (경로 A)',
    code: CODE_RESTORE_A, line: 12,
    path: 'A', stage: 'A_user',
    desc: '[경로 A] __restore → sret → 유저 모드 복귀\n\nsret 실행:\n  PC = sepc = ecall_pc + 4  ← 같은 앱의 다음 명령!\n  a0 = TrapContext.x[10]   ← syscall 반환값\n  mode = U-mode\n\n유저 앱 입장에서는:\n  ecall()이 마치 함수처럼 반환값을 돌려준 것으로 보입니다.',
    detail: '앱은 계속 실행됩니다. 다음 syscall 또는 예외가 발생하면 다시 __alltraps로 진입합니다.',
  },
  {
    title: '경로 B: StoreFault / IllegalInstruction',
    file: 'os/src/trap/mod.rs (경로 B)',
    code: CODE_TRAP_HANDLER, line: 15,
    path: 'B', stage: 'handler',
    desc: '[경로 B] 치명적 예외 처리\n\n  StoreFault: 유효하지 않은 주소에 쓰기 시도\n  StorePageFault: 페이지 권한 위반\n  IllegalInstruction: 잘못된 명령어\n\n이 경우 현재 앱을 종료하고 run_next_app()을 호출합니다.\n→ cx로 복귀하지 않고 완전히 새로운 앱을 시작합니다.',
    detail: 'Unsupported trap은 panic! — 커널 버그를 의미합니다.',
  },
  {
    title: '경로 B: run_next_app() → 다음 앱 적재',
    file: 'os/src/batch.rs :: run_next_app() (경로 B)',
    code: CODE_RUN_NEXT, line: 4,
    path: 'B', stage: 'B_load',
    desc: '[경로 B] run_next_app():\n\n1. load_app(current_app): 다음 앱 바이너리를 0x80400000에 복사\n2. move_to_next_app(): current_app += 1\n\n현재 앱의 TrapContext는 더 이상 사용하지 않습니다.\n새로운 앱을 위한 초기 TrapContext를 만들 것입니다.',
    detail: '만약 모든 앱이 끝나면 shutdown(false)를 호출하여 QEMU를 종료합니다.',
  },
  {
    title: '경로 B: 새 TrapContext → __restore → sret',
    file: 'os/src/batch.rs (경로 B)',
    code: CODE_RUN_NEXT, line: 8,
    path: 'B', stage: 'B_user',
    desc: '[경로 B] 새 앱을 위한 초기 TrapContext 생성:\n\n  app_init_context(0x80400000, user_stack_top)\n  push_context() → kernel stack에 배치\n  __restore(cx_ptr) → sret\n\nsret 실행:\n  PC = 0x80400000  ← 새 앱 진입점\n  mode = U-mode\n\n새 앱이 처음부터 실행됩니다!',
    detail: '경로 B는 ch3의 문맥 교환(context switch)과 다릅니다 — TaskContext 저장/복원 없이 단순히 다음 앱을 로드합니다.',
  },
];
